-- NEXORA Server
-- Execute este SQL no Supabase > SQL Editor

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  created_at timestamptz not null default now()
);

create unique index if not exists users_email_unique
on public.users (lower(email));

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  message text not null,
  created_at timestamptz not null default now()
);

alter table public.users enable row level security;
alter table public.messages enable row level security;

-- A API usa a SERVICE ROLE no backend, portanto não é necessário
-- expor permissões de escrita diretamente ao navegador.
